\c postgres;

CREATE DATABASE granulainbound OWNER fluance;

REVOKE ALL ON DATABASE granulainbound FROM PUBLIC;

\c granulainbound;

CREATE SCHEMA IF NOT EXISTS ehealth AUTHORIZATION fluance;

SET search_path TO ehealth;

REVOKE ALL ON SCHEMA ehealth FROM PUBLIC;

GRANT CONNECT ON DATABASE granulainbound TO dbinput;
GRANT USAGE ON SCHEMA ehealth TO dbinput;

ALTER DEFAULT PRIVILEGES IN SCHEMA ehealth GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO dbinput;
ALTER DEFAULT PRIVILEGES IN SCHEMA ehealth GRANT USAGE,SELECT ON SEQUENCES TO dbinput;
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
